version: '3'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules-store:/app/node_modules
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npm run unit
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules-store:/app/node_modules
volumes:
  node_modules-store:
